# Generated by Django 4.1.5 on 2023-03-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_sign_up_delete_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign_up',
            new_name='SignUp',
        ),
    ]
