# Generated by Django 4.1.5 on 2023-03-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_signup_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
